FROM nginx
LABEL github=https://github.com/macielsousadasilva
COPY /nginx.conf	/etc/nginx/nginx.conf
#COPY /server.crt	/etc/nginx/server.crt
#COPY /server.key	/etc/nginx/server.key
COPY /static	    /static
